name: mobile_lab_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.0
  math_expressions: ^2.6.0
  provider: ^6.1.5+1
  flutter_riverpod: ^2.6.1
  flutter_bloc: ^9.1.1
  http: ^1.6.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/hw05_layout_widget/
    - assets/images/w04_product_layout_app/
    - assets/images/w04_week4_app/
    - assets/images/w05_widget_tree/
    - assets/images/restaurant_food_image_menu/

  fonts:
    - family: Graphik Thai Loop
      fonts:
        - asset: assets/fonts/GraphikThaiLoop/GraphikThaiLoop-Regular.otf
        - asset: assets/fonts/GraphikThaiLoop/GraphikThaiLoop-Light.otf
        - asset: assets/fonts/GraphikThaiLoop/GraphikThaiLoop-Black.otf
        - asset: assets/fonts/GraphikThaiLoop/GraphikThaiLoop-Semibold.otf
          weight: 500
    - family: Kurale
      fonts: 
        - asset: assets/fonts/Kurale/Kurale-Regular.ttf
    - family: Roboto
      fonts: 
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
    - family: Leckerli One
      fonts: 
        - asset: assets/fonts/LeckerliOne-Regular.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
